### ISSUE TITLE
Can not run on browser

### ISSUE THREAD

**Issue by vinhphucit** [ClaytonFarr/sveltekit-netlify-stripe-fauna-example#1]
Hi Clayton Farr,

I cloned your project and run command `npm run dev`,  it showed success message  but I can not open the website on browser with that address , do you know why?. I created my own project from scratch to test if there is any issue with my developement enviroment and it works perfect
`  SvelteKit v1.0.0-next.229

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

`

**Comment by ClaytonFarr** [comment]
Hi @vinhphucit,

If you haven't already done so, you'll likely need to specify the version of SvelteKit that was current when this project was created (v115) and step forward from there to account for updates in how SvelteKit handles some things differently now -

Some notes here -
https://github.com/ClaytonFarr/sveltekit-netlify-stripe-fauna-example#implementation-steps

And details on what's changed since v115 to now -
https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

Regarding the `port` and `--host` specifically, I recall I had to do this to get the SvelteKit server to play nice with Netlify's dev server. It may not be necessary anymore, or unnecessary if you're not using Netlify CLI / dev server as well to connect local functions to your Netlify site. If you want to play with that, update the `dev` script in package.json.

Cheers
