### ISSUE TITLE
Netlify Identity uses GoTrue but requires an upgraded account

### ISSUE THREAD

**Issue by acatataca** [ClaytonFarr/sveltekit-netlify-stripe-fauna-example#2]
I'm getting started with sveltekit, gotrue, and supabase. Your starter seems like a great resource since gotrue-js (and supabase-js) rely on window (browser) which makes session handling with sveltekit (SSR) more difficult than it should be. Your approach to solving this is beautifully written by the way. 

My issue is that Netlify Identity requires an upgraded account ($99 per month) in order set the invitation, confirmation, recovery, and email change templates. I'd like to get the example working without having to pay $99 per month. 

The cloud gotrue server hosted by supabase seems like it will be just fine for what I want to do. 

Since it's not possible for me to run the example without upgrading my Netlify account, what changes do you recommend I make to bypass Netlify Identity?

Thank you,
Sam

**Comment by ClaytonFarr** [comment]
Hi @acatataca,

Thanks for the kind words. It's been a minute since I was mentally in this project, so I may be forgetting some details, but in general –

- I created this originally using the free Identity plan and it looks like the functionality offered is still the same
- You should be able to create custom email templates, similar to what you'll see in this repo in the `/src/auth_email_templates` directory; more detail from Netlify on doing this is at https://docs.netlify.com/visitor-access/identity/identity-generated-emails/#custom-templates
- The one limitation you'll hit re: emails on their free plan is not being able to customize the sender address; for this, you'd need to be on the $99/mo plan you mentioned.
- If you want to try and skip that you could either -
   1.  run and manage your own instance of GoTrue since Netlify has open-sourced it (https://github.com/netlify/gotrue)
   2. swap Netlify Identity out for another auth provider (e.g AuthO) that can create/manage JWTs. To do this you'd need to update the calls in this repo from Identity to their API for token creation, signing, etc and configure how it handles user communication. 

Hope that helps - good luck,
Clayton
